### ISSUE TITLE
Circular dependency in Node 14.x

### ISSUE THREAD

**Issue by ceecko** [signalfx/signalfx-nodejs#55]
Node `14.5.0` complains about a circular dependency due to `winston` module.

```
(node:18613) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:824:11)
    at Object.get (internal/modules/cjs/loader.js:838:5)
    at Object.exports.setLevels (/home/e-src/2020-07-11-20-20-21/node_modules/signalfx/node_modules/winston/lib/winston/common.js:35:14)
    at Object.<anonymous> (/home/e-src/2020-07-11-20-20-21/node_modules/signalfx/node_modules/winston/lib/winston.js:84:8)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
```

**Comment by jtmal-signalfx** [comment]
CI is now running successfully for all LTS versions (8, 10, 12, 14). I think it should be fine now.
